name: Build + Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      matrix:
        dotnet-version: ["9.0.x"]
        framework: ["net9.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: |
          dotnet publish ./Vibekiller/Vibekiller.csproj -c Release -f ${{ matrix.framework }} -r win-x64 --self-contained true -o publish_output

      - name: List published files
        run: dir publish_output

      - name: Zip published files
        run: |
          powershell Compress-Archive -Path publish_output\* -DestinationPath Vibekiller_Build_${{ github.run_id }}.zip
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VibekillerBuild
          path: Vibekiller_Build_${{ github.run_id }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Build-${{ github.run_id }}"
          name: "Build-${{ github.run_id }}"
          body: "Automated build"
          draft: false
          prerelease: false
          files: Vibekiller_Build_${{ github.run_id }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
